version: 2.1

orbs:
  gh: circleci/github-cli@2.3.0

jobs:
  build-jar:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - attach_workspace:
          at: ~/workspace
      - run: ./package.sh
      - persist_to_workspace:
          root: .
          paths:
            - providers

  publish-release:
    working_directory: ~/workspace
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - gh/setup
      - attach_workspace:
          at: ~/workspace
      - run: chmod +x ./publish-release.sh
      - run: ./publish-release.sh
workflows:
  publish:
    jobs:
      - build-jar
      - hold-release:
          name: hold-release
          type: approval
          requires:
            - build-jar
      - publish-release:
          requires:
            - hold-release