version: 2.1

orbs:
  gh: circleci/github-cli@2.3.0

jobs:
  build-jar:
    docker:
      - image: timbru31/java-node:8-jdk-20
    steps:
      - checkout
      - attach_workspace:
          at: ~/workspace
      - run: cd ./themes/custom-theme/theme/keycloak/common/resources && yarn install --production
      - run: ./package.sh
      - persist_to_workspace:
          root: .
          paths:
            - providers

  publish-staging-release:
    working_directory: ~/workspace
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - gh/setup
      - attach_workspace:
          at: ~/workspace
      - run: chmod +x ./publish-release.sh
      - run: ./publish-release.sh staging

workflows:
  version: 2
  build-and-publish-staging:
    jobs:
      - build-jar
      - publish-staging-release:
          requires:
            - build-jar